paper:
	pdflatex diversity_statement_jiang.tex
	pdflatex diversity_statement_jiang.tex
	make clean
	open diversity_statement_jiang.pdf

clean:
	\rm -f *.dvi *.ps *.bbl *.aux *.log *.blg *.toc all.tar* uu \
	*~ *.bak *.lbl *.brf *.out

spotless: clean
	\rm -f *.pdf
